[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/sanctum/csrf-cookie"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = true